/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vmc_ipc_config_VmcConfig */

#ifndef _Included_com_vmc_ipc_config_VmcConfig
#define _Included_com_vmc_ipc_config_VmcConfig
#ifdef __cplusplus
extern "C" {
#endif
#undef com_vmc_ipc_config_VmcConfig_DEFAULT_ISSTOREREMOTE
#define com_vmc_ipc_config_VmcConfig_DEFAULT_ISSTOREREMOTE 0L
#undef com_vmc_ipc_config_VmcConfig_DEFAULT_DECODEMODE
#define com_vmc_ipc_config_VmcConfig_DEFAULT_DECODEMODE 1L
#undef com_vmc_ipc_config_VmcConfig_DEFAULT_AUTOCONNECT2AVAILABLEAP
#define com_vmc_ipc_config_VmcConfig_DEFAULT_AUTOCONNECT2AVAILABLEAP 0L
/*
 * Class:     com_vmc_ipc_config_VmcConfig
 * Method:    isStoreRemote
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_vmc_ipc_config_VmcConfig_isStoreRemote
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_config_VmcConfig
 * Method:    setStoreRemote
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_config_VmcConfig_setStoreRemote
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_vmc_ipc_config_VmcConfig
 * Method:    getResolution
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vmc_ipc_config_VmcConfig_getResolution
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_config_VmcConfig
 * Method:    setResolution
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_config_VmcConfig_setResolution
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_vmc_ipc_config_VmcConfig
 * Method:    getDecodeMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_config_VmcConfig_getDecodeMode
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_config_VmcConfig
 * Method:    setDecodeMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_config_VmcConfig_setDecodeMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_vmc_ipc_config_VmcConfig
 * Method:    getBitrateControl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_config_VmcConfig_getBitrateControl
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_config_VmcConfig
 * Method:    setBitrateControl
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_config_VmcConfig_setBitrateControl
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_vmc_ipc_config_VmcConfig
 * Method:    initNativeConfig
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_config_VmcConfig_initNativeConfig
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
