/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vmc_ipc_view_gl_GLBGVideoSprite */

#ifndef _Included_com_vmc_ipc_view_gl_GLBGVideoSprite
#define _Included_com_vmc_ipc_view_gl_GLBGVideoSprite
#ifdef __cplusplus
extern "C" {
#endif
#undef com_vmc_ipc_view_gl_GLBGVideoSprite_VERTEX_BUFFER
#define com_vmc_ipc_view_gl_GLBGVideoSprite_VERTEX_BUFFER 0L
#undef com_vmc_ipc_view_gl_GLBGVideoSprite_INDEX_BUFFER
#define com_vmc_ipc_view_gl_GLBGVideoSprite_INDEX_BUFFER 1L
#undef com_vmc_ipc_view_gl_GLBGVideoSprite__COUNT
#define com_vmc_ipc_view_gl_GLBGVideoSprite__COUNT 4L
#undef com_vmc_ipc_view_gl_GLBGVideoSprite_VERTEX_COORDS_SIZE
#define com_vmc_ipc_view_gl_GLBGVideoSprite_VERTEX_COORDS_SIZE 3L
#undef com_vmc_ipc_view_gl_GLBGVideoSprite_TEXTURE_COORDS_SIZE
#define com_vmc_ipc_view_gl_GLBGVideoSprite_TEXTURE_COORDS_SIZE 2L
#undef com_vmc_ipc_view_gl_GLBGVideoSprite_FLOAT_SIZE_BYTES
#define com_vmc_ipc_view_gl_GLBGVideoSprite_FLOAT_SIZE_BYTES 4L
/*
 * Class:     com_vmc_ipc_view_gl_GLBGVideoSprite
 * Method:    onUpdateVideoTextureNative
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vmc_ipc_view_gl_GLBGVideoSprite_onUpdateVideoTextureNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_vmc_ipc_view_gl_GLBGVideoSprite
 * Method:    onSurfaceCreatedNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_view_gl_GLBGVideoSprite_onSurfaceCreatedNative
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_view_gl_GLBGVideoSprite
 * Method:    onSurfaceChangedNative
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_view_gl_GLBGVideoSprite_onSurfaceChangedNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_vmc_ipc_view_gl_GLBGVideoSprite
 * Method:    getVideoFrameNative
 * Signature: (Landroid/graphics/Bitmap;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vmc_ipc_view_gl_GLBGVideoSprite_getVideoFrameNative
  (JNIEnv *, jobject, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
