/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vmc_ipc_proxy_IpcProxy */

#ifndef _Included_com_vmc_ipc_proxy_IpcProxy
#define _Included_com_vmc_ipc_proxy_IpcProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_connect
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_pause
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    resume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_resume
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    triggerTakeOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_triggerTakeOff
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    startPreview
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_startPreview
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    stopPreview
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_stopPreview
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    onSizeChange
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_onSizeChange
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    takePhoto
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_takePhoto
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    startRecord
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_startRecord
  (JNIEnv *, jobject, jstring, jstring, jstring, jboolean);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    stopRecord
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_stopRecord
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    takeNavDataSnapshot
 * Signature: (Lcom/vmc/ipc/proxy/NavData;)Lcom/vmc/ipc/proxy/NavData;
 */
JNIEXPORT jobject JNICALL Java_com_vmc_ipc_proxy_IpcProxy_takeNavDataSnapshot
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    setControlParameter
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_setControlParameter
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    takeConfigSnapshot
 * Signature: (Lcom/vmc/ipc/proxy/VIConfig;)Lcom/vmc/ipc/proxy/VIConfig;
 */
JNIEXPORT jobject JNICALL Java_com_vmc_ipc_proxy_IpcProxy_takeConfigSnapshot
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    getConfigItem
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vmc_ipc_proxy_IpcProxy_getConfigItem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    setConfigItem
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_setConfigItem
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_vmc_ipc_proxy_IpcProxy
 * Method:    resetConfig
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_proxy_IpcProxy_resetConfig
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
