/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vmc_ipc_ftp_FTPClient */

#ifndef _Included_com_vmc_ipc_ftp_FTPClient
#define _Included_com_vmc_ipc_ftp_FTPClient
#ifdef __cplusplus
extern "C" {
#endif
#undef com_vmc_ipc_ftp_FTPClient_FTP_CONNECT_MODE_PASV
#define com_vmc_ipc_ftp_FTPClient_FTP_CONNECT_MODE_PASV 1L
#undef com_vmc_ipc_ftp_FTPClient_FTP_CONNECT_MODE_PORT
#define com_vmc_ipc_ftp_FTPClient_FTP_CONNECT_MODE_PORT 2L
#undef com_vmc_ipc_ftp_FTPClient_FTP_TRANSFER_MODE_ASCII
#define com_vmc_ipc_ftp_FTPClient_FTP_TRANSFER_MODE_ASCII 65L
#undef com_vmc_ipc_ftp_FTPClient_FTP_TRANSFER_MODE_IMAGE
#define com_vmc_ipc_ftp_FTPClient_FTP_TRANSFER_MODE_IMAGE 73L
/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpInit
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpLastResponse
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpLastResponse
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpSysType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpSysType
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpSize
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpSize
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpModDate
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpModDate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpSetCallback
 * Signature: (Lcom/vmc/ipc/ftp/FTPClient/FtpCallbackListener;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpSetCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpClearCallback
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpClearCallback
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpConnect
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpConnect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpLogin
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpQuit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpQuit
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpSetConnectionMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpSetConnectionMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpChdir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpChdir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpMkDir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpMkDir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpRmdir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpRmdir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpDir
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpDir
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpNlst
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpNlst
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpCDUp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpCDUp
  (JNIEnv *, jobject);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpPwd
 * Signature: ()Ljava/lang/String
 */
JNIEXPORT jstring JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpPwd
  (JNIEnv *env, jobject);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpGet
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpGet
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpPut
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpPut
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpDelete
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpDelete
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_vmc_ipc_ftp_FTPClient
 * Method:    FtpRename
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_vmc_ipc_ftp_FTPClient_FtpRename
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
